[titulo]
name = "Central America Finals"
codes = ["teamca"]

[[sedes]]
name = "Central America Finals"
codes = ["teamca"]

[[sedes]]
codes = ["teamcacr"]
name = "Costa Rica Site"

[[sedes]]
codes = ["teamcael"]
name = "El Salvador Site"

[[sedes]]
codes = ["teamcagt"]
name = "Guatemala Site"
