[titulo]
name = "South America - North Finals"
codes = ["teamno"]

[[sedes]]
name = "South America - North Finals"
codes = ["teamno"]

[[sedes]]
codes = ["teamnoco"]
name = "Colombia"

[[sedes]]
codes = ["teamnoec"]
name = "Ecuador"

[[sedes]]
codes = ["teamnovz"]
name = "Venezuela"
