[titulo]
name = "South America - South Finals - Invitados"
codes = ["cclso"]

[[sedes]]
name = "South America - South Finals - Invitados"
codes = ["cclso"]

[[sedes]]
codes = ["cclsoar"]
name = "CCL Argentina"

[[sedes]]
codes = ["cclsobo"]
name = "CCL Bolivia"

[[sedes]]
codes = ["cclsoch"]
name = "CCL Chile"

[[sedes]]
codes = ["cclsopa", "cclsope"]
name = "CCL Peru"

[[sedes]]
codes = ["cclsopa"]
name = "CCL Peru - Arequipa"

[[sedes]]
codes = ["cclsope"]
name = "CCL Peru - Lima"
