titulo = "Maratona de Programação da SBC - 2ª fase"

# br - Brasil
[[sedes]]
name = "Brasil"
premiacao = true
vagas = 5
codes = ["teambr"]

[[sedes]]
name = "América Latina"
codes = ["team"]
premiacao = false
vagas = 0
