titulo = "Maratona de Programação da SBC - 1ª fase"

[[sedes]]
name = "Acre"
codes = ["teambrac"]
premiacao = false
vagas = 0

[[sedes]]
name = "Alagoas"
codes = ["teambral"]
premiacao = false
vagas = 0

[[sedes]]
name = "Amazonas"
codes = ["teambram"]
premiacao = false
vagas = 0

[[sedes]]
name = "Amapá"
codes = ["teambrap"]
premiacao = false
vagas = 0

[[sedes]]
name = "Bahia"
codes = ["teambrba"]
premiacao = true
vagas = 2

[[sedes]]
name = "Ceará"
codes = ["teambrce"]
premiacao = true
vagas = 2

[[sedes]]
name = "Distrito Federal"
codes = ["teambrdf"]
premiacao = false
vagas = 0

[[sedes]]
name = "Espírito Santo"
codes = ["teambres"]
premiacao = false
vagas = 0

[[sedes]]
name = "Goiás"
codes = ["teambrgo"]
premiacao = false
vagas = 0

[[sedes]]
name = "Maranhão"
codes = ["teambrma"]
premiacao = false
vagas = 0

[[sedes]]
name = "Minas Gerais"
codes = ["teambrmg"]
premiacao = true
vagas = 7

[[sedes]]
name = "Mato Grosso do Sul"
codes = ["teambrms"]
premiacao = false
vagas = 0

[[sedes]]
name = "Mato Grosso"
codes = ["teambrmt"]
premiacao = false
vagas = 0

[[sedes]]
name = "Pará"
codes = ["teambrpa"]
premiacao = false
vagas = 0

[[sedes]]
name = "Paraíba"
codes = ["teambrpb"]
premiacao = true
vagas = 2

[[sedes]]
name = "Pernambuco"
codes = ["teambrpe"]
premiacao = false
vagas = 0

[[sedes]]
name = "Piauí"
codes = ["teambrpi"]
premiacao = false
vagas = 2

[[sedes]]
name = "Paraná"
codes = ["teambrpr"]
premiacao = true
vagas = 2

[[sedes]]
name = "Rio de Janeiro"
codes = ["teambrrj"]
premiacao = true
vagas = 4

[[sedes]]
name = "Rio Grande do Norte"
codes = ["teambrrn"]
premiacao = false
vagas = 0

[[sedes]]
name = "Rondônia"
codes = ["teambrro"]
premiacao = false
vagas = 0

[[sedes]]
name = "Roraima"
codes = ["teambrrr"]
premiacao = false
vagas = 0

[[sedes]]
name = "Rio Grande do Sul"
codes = ["teambrrs"]
premiacao = false
vagas = 0

[[sedes]]
name = "Santa Catarina"
codes = ["teambrsc"]
premiacao = true
vagas = 2

[[sedes]]
name = "Sergipe"
codes = ["teambrse"]
premiacao = false
vagas = 0

[[sedes]]
name = "São Paulo"
codes = ["teambrsp"]
premiacao = true
vagas = 8


[[sedes]]
name = "Tocantins"
codes = ["teambrto"]
premiacao = false
vagas = 0

[[sedes]]
name = "Supersede Centro-Oeste"
premiacao = true
vagas = 3
codes = ["teambrdf", "teambrgo", "teambrmt", "teambrms"]

[[sedes]]
name = "Supersede Nordeste"
premiacao = true
vagas = 3
codes = ["teambral", "teambrma", "teambrpe", "teambrrn", "teambrse"]

[[sedes]]
name = "Supersede Norte"
premiacao = true
vagas = 2
codes = [
    "teambrac",
    "teambrap",
    "teambram",
    "teambrpa",
    "teambrro",
    "teambrrr",
    "teambrto",
]

[[sedes]]
name = "Supersede Brasil"
premiacao = true
vagas = 2
codes = ["teambres", "teambrrs"]

[[sedes]]
name = "Brasil"
codes = ["teambr"]
premiacao = false
vagas = 0
ouro = 3
prata = 6
bronze = 10
